// Generated by CoffeeScript 1.9.2
(function() {
  var APP_ID, AlgoliaSearch, HITS_PER_PAGE, INDEX_NAME, SEARCH_ONLY_API_KEY, Search,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  APP_ID = "A6LX075BLV";

  SEARCH_ONLY_API_KEY = "164c63eedb7efb07d13443812d592944";

  INDEX_NAME = "phenotype";

  HITS_PER_PAGE = 50;

  Search = (function() {
    function Search() {
      this.hitTemplate = Hogan.compile($('#hit-template').text());
    }

    Search.prototype.hits = function(content) {};

    Search.prototype.onSuccess = function(content) {
      this.renderHits(content);
      return $("#filter").css('background-color', '#fff');
    };

    Search.prototype.onError = function(err) {
      console.log(err);
      return $("#filter").css('background-color', '#fdd');
    };

    Search.prototype.renderHits = function(content) {
      var header, header_fields, hit, hitsHtml, i, j, len, ref, x;
      hitsHtml = '<table id="trait_table">';
      header_fields = ['Record ID', 'Description', 'Authors', 'Year', 'LRS', 'LRS location', 'Additive effect'];
      header = ((function() {
        var j, len, results;
        results = [];
        for (j = 0, len = header_fields.length; j < len; j++) {
          x = header_fields[j];
          results.push('<th>' + x + '</th>');
        }
        return results;
      })()).join('');
      hitsHtml += '<thead><tr>' + header + '</tr></thead><tbody>';
      ref = this.hits(content);
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        hit = ref[i];
        hitsHtml += this.hitTemplate.render(hit);
      }
      hitsHtml += '</tbody></table>';
      if (content.hits.length === 0) {
        hitsHtml = '<p id="no-hits">We didn\'t find any phenotypes for your search.</p>';
      }
      $("#hits").html(hitsHtml);
      return $('#trait_table').dataTable({
        columns: [
          {
            type: "num",
            swidth: "5%"
          }, {
            sWidth: "35%"
          }, {
            sWidth: "20%"
          }, null, {
            type: "num"
          }, {
            type: "natural"
          }, {
            type: "num"
          }
        ],
        sDom: "tir",
        iDisplayLength: -1,
        autoWidth: true,
        bLengthChange: true,
        bDeferRender: true,
        bSortClasses: false
      });
    };

    return Search;

  })();

  AlgoliaSearch = (function(superClass) {
    extend(AlgoliaSearch, superClass);

    function AlgoliaSearch() {
      AlgoliaSearch.__super__.constructor.apply(this, arguments);
      this.client = algoliasearch(APP_ID, SEARCH_ONLY_API_KEY);
      this.pheno_index = this.client.initIndex(INDEX_NAME);
      this.params = {
        hitsPerPage: HITS_PER_PAGE,
        advancedSyntax: true
      };
    }

    AlgoliaSearch.prototype.performSearch = function() {
      var query, query_params;
      query = $("#q").val();
      query_params = $.extend({}, this.params);
      query_params.numericFilters = $("#filter").val();
      return this.pheno_index.search(query, query_params).then((function(_this) {
        return function(c) {
          return _this.onSuccess(c);
        };
      })(this))["catch"]((function(_this) {
        return function(e) {
          return _this.onError(e);
        };
      })(this));
    };

    AlgoliaSearch.prototype.hits = function(content) {
      var e, h, hit, j, len, ref;
      h = [];
      ref = content.hits;
      for (j = 0, len = ref.length; j < len; j++) {
        hit = ref[j];
        hit.description = hit._highlightResult.Post_publication_description.value;
        hit.LRS = parseFloat(hit.LRS.toFixed(3));
        if (hit.Mb > 1e6) {
          hit.Mb /= 1e6;
        }
        hit.LRS_location = "Chr " + hit.Chr + ": " + (hit.Mb.toFixed(6)) + " Mb";
        try {
          hit.additive = parseFloat(hit.additive).toFixed(3);
        } catch (_error) {
          e = _error;
          hit.additive = null;
        }
        h.push(hit);
      }
      return h;
    };

    return AlgoliaSearch;

  })(Search);

  $(function() {
    var client;
    client = new AlgoliaSearch;
    $("#q").on('keyup', (function(_this) {
      return function() {
        return client.performSearch();
      };
    })(this));
    $("#filter").on('keyup', (function(_this) {
      return function() {
        return client.performSearch();
      };
    })(this));
    return $("#q").focus();
  });

}).call(this);
